### ISSUE TITLE
Tried to upload in app store. Showing some debugging related error. Kindly help to solve the issue.

### ISSUE THREAD

**Issue by cinoey** [successtar/web-to-app#1]

**Comment by successtar** [comment]
Can you please provide the error

The app below is built with the source code and currently live on play store
https://play.google.com/store/apps/details?id=co.streamcomm.video.streamcomm

**Comment by cinoey** [comment]
fwd the error message i got

---------- Forwarded message ---------
From: Google Play Support <no-reply-googleplay-developer@google.com>
Date: Sat, Jul 25, 2020 at 11:26 PM
Subject: Action Required: Your app is not compliant with Google Play
Policies (OkMaddy)
To: <okmaddy.app@gmail.com>
Cc: <okmaddy.app@gmail.com>




[image: Google Play] Developer update


Hi Developers at Streetkarma Pvt Ltd,
After a recent review, we found that your app OkMaddy
(com.myexampoint.webtoapp) is not compliant with one or more of our
Developer Program Policies. See below for more information about your app’s
status and how to correct the issue.
[image: Reasons of violation]
Issue with your app
Your app contains content that doesn't comply with the Webviews and
Affiliate Spam policy.

*Issue details*
We found an issue in the following area(s):

   - *In-app experience*: Please see attached screenshot
   com.myexampoint.webtoapp-InAppExperience-243.png

[image: Reasons of violation]
About the Webviews and Affiliate Spam policy
We don’t allow apps whose primary purpose is to drive affiliate traffic to
a website or provide a webview of a website without permission from the
website owner or administrator.
[image: Publishing Status]
App status: Suspended
Your app has been suspended and removed due to this policy issue.
Action required: Publish a new compliant version of your app
Here’s what to do to help get your app on Google Play:
1. Read through the Webviews and Affiliate Spam
<https://www.google.com/appserve/mkt/p/AD-FnEyrWTCUq7SySsVDSAhOX9EbdZZ3z-WlOm8-uIYgI-PS-z6gtGaSqgUMTH18Bf0heeJhKiqlvjKu3OIM9nI-rrHOT4xQkIW73MT0mp3FfXj3C996HKWbRNcv-VIex5H--af5l461HOPMVkdpQUVfg6xdOwOBmzZFRMU1>
policy
for more details.
2. If it’s possible to bring your app into compliance, make appropriate
changes to your app. In addition to addressing the issue identified above,
you may also want to check your app’s store listing for compliance, if
applicable.
3. Double check that your app is compliant with all other Developer Program
Policies
<https://www.google.com/appserve/mkt/p/AD-FnEyDjjtfv_dnTJLXAyFhzB7Xa77TSAwojEFbsj4oyeQCgDkjFnpyO0eOeYBBHfnybRdOBQAArWNNKDRwMcRfk80l_Sppz_OUat5N5Kx-EW-vhjNtEB-EBXuGJl3M>
.
4. Sign in to your Play Console
<https://www.google.com/appserve/mkt/p/AD-FnExoTLxWg8iWWtU19pSr4zmvtOgMfiRxOzt34K-pAV9GDiQp6-HAVg9yzlZWbpezTuPiDzP9TZA6IB64K6zvrIEW8bMVmQE>
and submit the updated, policy compliant app using a new package name and a
new app name.
Please note that additional suspensions of any nature may result in the
termination
<https://www.google.com/appserve/mkt/p/AD-FnEzRFDcKv7MmhV4hfa3wM5cCOSxhTKqfyp9PBjF0jiqL1CpwsF0fkhrvQafrpCQogwiWUIHBZQ_1TfoZbvp6pSxfUAaY-6JhEd-hlzBrNapQgdi8Jb4cq_YcgpPUFSf4LpWyCj1mftc>
of your developer account, and investigation and possible termination of
related Google accounts.
Contact support
If you’ve reviewed the policy and feel our decision may have been in error,
please reach out to our policy support team
<https://www.google.com/appserve/mkt/p/AD-FnEz3M1ysq7E1xZtyEy_BrLmTfiGxK49CygAJKuQjgd5UdHXb7AiGgAUnwPyW-QnQy82mVAP-GmSE18A1FB-iZf_uV5TqPyNTeJtFOj2OHb29-RQzWopnpdGwAZaFNAKwG6EpDmbuRoLSW95eYnx7hoh3HCb91Z25s8GUc6l-70s-l7yljMgy9CnEmpBsyQFnhs5cmq0EduJyCLwbJFVv0JqoebBeBIDF-nsybPH3GJu9e25I9px0iYREb9n7L1_0MN9SXP1ie2OQWEdHSJs>.
We’ll get back to you within 2 business days.
Thanks for your continued support in helping to make Google Play a positive
experience for both developers and consumers. We look forward to seeing an
updated version of your app on Google Play.
*Please complete a two question survey
<https://www.google.com/appserve/mkt/p/AD-FnEwLIQv64ZuiAUTMxZ2q5rhgYbP0_AVi9hgVU0cD5s9WvdbvywChojHhjKAbdtsV504R3-_FiPpJdpJi45XvCS6T4z1A7WSXRtSrH4okxzd_k4Jfu_fE_ETO_uv5o_VQVd4ZUB3uSvIPadv6FWdgcIdOhJ4vB_Egs1_XsSWR_R-Sv2A-idCLsIjCT7AsheE_JP-X6KDKPUh-WQFOwFk>
to help us improve this experience.*
The Google Play Team
<https://www.google.com/appserve/mkt/p/AD-FnEz8T_Njaf9U5FtpBrLwt4EQ8sg50Zt9aGaw8b6BzEFWSx9QQWtnotsEUwcCVHjZK22DO_bzMDqdYFC6P2Me8LyiKvsSlfp9zSXYOiHQiwLFB3bWEM7bZWomyRcTfnrchOIdM6R91G7zrZbe6fY1JxWu3wGxYdH7YbQUwH1ybju-9ssLWueTInbOA0-CPM9hvu--QvNSSxAlI_IXqnGOO3Q>
© 2020 Google LLC 1600 Amphitheatre Parkway, Mountain View, CA 94043

Update your marketing preferences
<https://www.google.com/appserve/mkt/p/AD-FnEwm7rlkP7EdRWp_RuINmsaYOylwOpILaP-BXRUS7RzG1KNbLibar_ThqD8BINvutUlBr70xDSc0TkhM5Abw>
to receive the latest news and tips.

You have received this mandatory email service announcement to update you
about important changes to your Google Play Developer account.

**Comment by successtar** [comment]
I think it as to do with copyright issues

Hi Developers at Streetkarma Pvt Ltd,
After a recent review, we found that your app OkMaddy
(**com.myexampoint.webtoapp**) is not compliant with one or more of our
Developer Program Policies. See below for more information about your app’s
status and how to correct the issue.
[image: Reasons of violation]
Issue with your app
Your app contains content that doesn't comply with the Webviews and
Affiliate Spam policy.

Which can be linked to this naming **com.myexampoint.webtoapp** you will need to change this to match the domain of the site you want to use in the app.

You need to update your manifest file, build.gradle file in app directory and path directory to reflect your domain and not com.myexampoint.webtoapp

This will allow Google to not see the app as a spam or pirated version.

The app on playstore https://play.google.com/store/apps/details?id= **co.streamcomm.video.streamcomm** match the app naming with the webview url.

**Comment by cinoey** [comment]
Thanks! So if i change manifest and path directory... and reupload the app
it might work right... Any other issue you think?

"You need to update your manifest and path directory to reflect your domain
and not com.myexampoint."

**Comment by successtar** [comment]
And the applicationId in app build.gradle file

**Comment by cinoey** [comment]
Thanks a lot for the support i'll make all changes and try uploading
again...
