### ISSUE TITLE
not redirect to own website

### ISSUE THREAD

**Issue by dotnethabib** [successtar/web-to-app#10]
Dear Mr.
Thank you for making this website to apk apps, the problem is you mention in readme file that mainactivity java file there is a url that url should be changed, but after changing url and save it and installing apk and when i open the apps it redirect to your own apps

**Comment by successtar** [comment]
Confirm you have changed the Url on line 22 of this file https://github.com/successtar/web-to-app/blob/master/app/src/main/java/com/myexampoint/webtoapp/MainActivity.java as indicated, then compile the code to apk and test
