### ISSUE TITLE
Old webpage loads

### ISSUE THREAD

**Issue by Exanoff12** [successtar/web-to-app#11]
So when i open the app once and load the current page the next time the same page opens even when i update the website. This happens beacuse of web cache & cookies. Can you please make this that it clears the cache & cookies everytime you exit from the app. Please you are a very nice person. Please do it for me. 🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏

**Comment by successtar** [comment]
I am not clear with your message.

Can you add screenshots?

**Comment by Exanoff12** [comment]
> I am not clear with your message.
> 
> Can you add screenshots?

So basically what I am trying to tell you is explained below:

My app contains the link of my GitHub hosted site. So if I open the app the link loads. Then I close the app. After that I update something in my GitHub hosted site. Then I reopen the app and it shows the old cached page not the new updated one. I have cleared the cache of the app and then it reloads the updated app. So can you please make it that it cleares the cache everytime I close the app.
