### ISSUE TITLE
How to install 

### ISSUE THREAD

**Issue by Manishfoodtechs** [successtar/web-to-app#12]
Hello, this seems to be good for non Android people. Can anyone tell installation instructions ?

**Comment by successtar** [comment]
You question is not clear

**Comment by Jipok** [comment]
I also had a lot of trouble when I tried to build this. Simply because I have 0 experience in android development and java. After much suffering, I implemented tool that does not require anything from the user except to set the desired url or other settings: https://github.com/Jipok/website-to-apk
