### ISSUE TITLE
No variants found for 'app'. Check build files to ensure at least one variant exists.

### ISSUE THREAD

**Issue by FaisalAhmed123** [successtar/web-to-app#9]
I am getting this error when trying to build in latest version of Android studio 
`No variants found for 'app'. Check build files to ensure at least one variant exists.`

**Comment by FaisalAhmed123** [comment]
![image](https://user-images.githubusercontent.com/59764708/111543175-9a4db880-876a-11eb-9e04-f8ae6fb74afa.png)

**Comment by successtar** [comment]
Confirm if this solve the problem https://stackoverflow.com/questions/64366729/android-studio-no-build-variant-found-error
